apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "demoapp.fullname" . }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ template "demoapp.name" . }}
    app: {{ template "demoapp.name" . }}
    chart: {{ template "demoapp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

data:
 {{- (.Files.Glob "../files/config").AsConfig | nindent 2 }}
