apiVersion: v1
kind: Service
metadata:
  name: {{ include "demoapp.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "demoapp.name" . }}
    helm.sh/chart: {{ include "demoapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app: {{ template "demoapp.name" . }}
    chart: {{ template "demoapp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

spec:
  type: {{ .Values.appService.type }}
  ports:
  - port: {{ .Values.appService.internalPort }}
    targetPort: {{ .Values.appService.internalPort }}
    protocol: TCP
    name: {{ .Values.appService.name }}
  selector:
    app: {{ template "demoapp.fullname" . }}
